FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL=http://localhost:3000/api/v1
ARG VITE_IMAGEKIT_PUBLIC_KEY=
ARG VITE_IMAGEKIT_URL_ENDPOINT=
ARG VITE_IMAGEKIT_AUTH_ENDPOINT=/uploads/imagekit-auth
ARG VITE_COMPANY_NAME="EJGH AUTO IMPORT SRL"
ARG VITE_COMPANY_RNC=
ARG VITE_COMPANY_ADDRESS=
ARG VITE_COMPANY_CITY="Republica Dominicana"
ARG VITE_COMPANY_PHONE=
ARG VITE_COMPANY_EMAIL=
ARG VITE_COMPANY_WEBSITE=
ARG VITE_INVOICE_TAX_RATE=0
ARG VITE_INVOICE_TAX_LABEL=ITBIS
ARG VITE_INVOICE_TAX_INCLUDED=true
ARG VITE_INVOICE_FOOTER_NOTE=

ENV VITE_API_URL=${VITE_API_URL} \
    VITE_IMAGEKIT_PUBLIC_KEY=${VITE_IMAGEKIT_PUBLIC_KEY} \
    VITE_IMAGEKIT_URL_ENDPOINT=${VITE_IMAGEKIT_URL_ENDPOINT} \
    VITE_IMAGEKIT_AUTH_ENDPOINT=${VITE_IMAGEKIT_AUTH_ENDPOINT} \
    VITE_COMPANY_NAME=${VITE_COMPANY_NAME} \
    VITE_COMPANY_RNC=${VITE_COMPANY_RNC} \
    VITE_COMPANY_ADDRESS=${VITE_COMPANY_ADDRESS} \
    VITE_COMPANY_CITY=${VITE_COMPANY_CITY} \
    VITE_COMPANY_PHONE=${VITE_COMPANY_PHONE} \
    VITE_COMPANY_EMAIL=${VITE_COMPANY_EMAIL} \
    VITE_COMPANY_WEBSITE=${VITE_COMPANY_WEBSITE} \
    VITE_INVOICE_TAX_RATE=${VITE_INVOICE_TAX_RATE} \
    VITE_INVOICE_TAX_LABEL=${VITE_INVOICE_TAX_LABEL} \
    VITE_INVOICE_TAX_INCLUDED=${VITE_INVOICE_TAX_INCLUDED} \
    VITE_INVOICE_FOOTER_NOTE=${VITE_INVOICE_FOOTER_NOTE}

RUN npm run build

FROM nginx:alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1/health || exit 1

CMD ["nginx", "-g", "daemon off;"]
